### ISSUE TITLE
[Feature] transmission port

### ISSUE THREAD

**Issue by ctyjiuh** [corporateanon/telegram-transmission-bot#14]
Please add feature to explicitly specify transmission port in client (telegram-transmission-bot service). It comes valuable when connecting to transmission server from remote machine through nat

**Comment by corporateanon** [comment]
ok, i'll do that

**Comment by corporateanon** [comment]
@ctyjiuh try now tag 1.2.5

**Comment by corporateanon** [comment]
Fixed and verified.
